### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by KyrillosL** [TheKingElessar/iDeemYouWorthy#1]
Hi, and thanks for this repo. 
Unfortunately, I can't run it as it's missing a requirements.txt file (and especially the version of deemix). 
Could you add one please ? 

Thanks a lot

**Comment by KyrillosL** [comment]
Well, I guess it's for windows only as it requires `win32com` to load Itunes playlists.

**Comment by TheNathanSpace** [comment]
Yes, I guess that does restrict it to Windows only, sorry. If there's another playlist format you want it's probably simple enough to add that functionality (let me know if you want me to look into it). Since `win32com` is only required for the iTunes functionality you might still find some use out of this?

**Comment by TheNathanSpace** [comment]
[Added `requirements.txt`](https://github.com/TheKingElessar/iDeemYouWorthy/commit/fbf517a08f3fc410830276c583e15d3926f03309)

**Comment by TheNathanSpace** [comment]
> 
> 
> Well, I guess it's for windows only as it requires `win32com` to load Itunes playlists.

Hey @KyrillosL if you still have a use for this, I've made some changes to make it more useful for Android. One of these is improving the m3u playlist generation. This reduces its dependency on `win32com`, since you can use the m3u files directly or drag and drop them into iTunes. 

So overall, it's not necessarily Windows only now (although it hasn't been tested elsewhere)! Just thought I'd let you know!
